name: aceup
description: Learn on the go!.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  material_design_icons_flutter: 3.2.4096
  flutter_tex: ^1.0.9
  flutter_html: ^0.10.4
  photo_view: ^0.4.2
  cached_network_image: ^1.1.1
  scoped_model: ^1.0.1
  toast: ^0.1.5
  flutter_secure_storage: ^3.2.1+1
  sqflite:
  shared_preferences: ^0.5.3+4
  path:
  http: ^0.12.0+2
  background_fetch: '^0.1.0'
  # provider: ^2.0.1
  # connectivity: ^0.4.3+1

dev_dependencies:
  flutter_launcher_icons: "^0.7.2"
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/1.jpeg
    - assets/2.jpeg
    - assets/3.jpeg
    - assets/4.jpeg
    - assets/5.jpeg
    - assets/chemistry.png
    - assets/mth-101.png
    - assets/mth-105.png
    - assets/playground.png
    - assets/avatars/001.png
    - assets/avatars/002.png
    - assets/avatars/003.png
    - assets/avatars/004.png
    - assets/avatars/005.png
    - assets/avatars/006.png
    - assets/avatars/007.png
    - assets/avatars/008.png
    - assets/avatars/009.png
    - assets/avatars/010.png
    - assets/quiz-icon.png
    - assets/hurray.png
    - assets/gt60.png
    - assets/lt60.png
    - assets/aceup-circle-icon.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: karla
      fonts:
        - asset: assets/fonts/Karla-Regular.ttf
        - asset: assets/fonts/Karla-Italic.ttf
          style: italic
        - asset: assets/fonts/Karla-Bold.ttf
          weight: 700
        - asset: assets/fonts/Karla-BoldItalic.ttf
          weight: 700
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/aceup-circle-icon.png"

analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true